#!/usr/bin/env zsh
setopt shwordsplit

LOCKFILE=/get_ip.lock
if [ -e $LOCKFILE ] && kill -0 $(cat $LOCKFILE); then
  exit 1
fi

trap "rm -f $LOCKFILE; exit" INT TERM EXIT
echo $$ > $LOCKFILE

IP_URLS=${IP_URLS:- \
    https://ifconfig.me/ip \
    http://ip1.dynupdate.no-ip.com:8245 \
    http://ip1.dynupdate.no-ip.com \
    https://api.ipify.org \
    https://diagnostic.opendns.com/myip \
    https://domains.google.com/checkip \
    https://ifconfig.io/ip \
    https://ipinfo.io/ip \
}

get_ip(){
  # Convert to array
  IP_URLS=("${(z)IP_URLS}")

  # Get random index
  I=$[$RANDOM % $#IP_URLS + 1]

  # Get random url from the list of urls
  IP_URL="${IP_URLS[$I]}"
  IP_URL="${IP_URL/BASE_IP/$(base_ip)}"
  IP_URL="${IP_URL/INTERNAL_IP/$(hostname -i)}"
  IP_URL="${IP_URL/HOSTNAME/$(hostname)}"

  curl -sS -k -m 10 "$@" "${IP_URL}" | grep -E '[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+'
}

ip=$(get_ip -s)
if [ -n "$ip" ]; then
    echo "$ip"
    exit
fi

while true; do
  >&2 date
  ip=$(get_ip)
  if [ -n "$ip" ]; then
    echo "$ip"
    rm -f $LOCKFILE
    exit
  else
    sleep 1
  fi
done
