#!/usr/bin/env zsh
set -e

date
echo "proxy url: socks5h://127.0.0.1:1080"
echo "config: $VPN_FILE"
base_ip

# Compatibility with older format
VPN_USER=${VPN_USER:-$USER}
VPN_PASS=${VPN_PASS:-$PASSWORD}
INTERFACE=${INTERFACE:$(ip -o -4 route show to default | awk '{print $5}')}

if [ "$SHELL" ]; then
  OPENVPN_ARGS="--daemon"
else
  OPENVPN_ARGS=""
fi

# Create OpenVPN files
mkdir -p /dev/net
mknod /dev/net/tun c 10 200

# Backup the resolv.conf to restore when the connection goes down
cp /etc/resolv.conf{,.backup}

echo "openvpn args: $OPENVPN_ARGS"

export HTTP_PROXY=socks5h://127.0.0.1:1080
export HTTPS_PROXY=socks5h://127.0.0.1:1080

# Start openvpn and echo show the command
set -v
timeout $TIMEOUT openvpn \
  $OPENVPN_ARGS \
  --config "$VPN_FILE" \
  --script-security 2 \
  --up /scripts/up \
  --route-up /scripts/route-up \
  --route-delay 1 \
  --route-pre-down /scripts/down \
  --up-restart \
  --ping 10 \
  --ping-restart 10 \
  --persist-tun \
  --auth-user-pass <(echo -e "$VPN_USER\n$VPN_PASS")

# Wait until VPN says we're up
while [ ! -f /up ]; do
  sleep 1
done

echo "vpn ip: $(get_ip)"

exec zsh
