#!/usr/bin/env zsh
set -v
echo "route up"

default_route=($(cat /default_route))
gateway=${default_route[3]}
interface=${default_route[5]}

export $(cat /env | xargs)

/sbin/ip -o -4 route add $PRIVATE_NET via $gateway dev $interface
echo $route_cmd add $PRIVATE_NET via $gateway dev $interface >> log

/usr/sbin/sockd -D
date > /up
